### ISSUE TITLE
pfam.php is not able to save a family name to db

### ISSUE THREAD

**Issue by baichuan1** [johngtoop/pathfinderweb16#5]
Hi @johngtoop I don't see the saving of family members happening yet.  Please fix!

**Comment by johngtoop** [comment]
Yes, How about you work on this @baichuan1 and I'll keep working on ped.php if you don't mind

**Comment by johngtoop** [comment]
It's now able to save a family and edit it too.

**Comment by johngtoop** [comment]
Fixed
